from enum import StrEnum


class RunState(StrEnum):
    CREATED = "CREATED"
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"
    CANCELLED = "CANCELLED"
    ORPHANED = "ORPHANED"


class ResumeMode(StrEnum):
    NATIVE = "NATIVE"
    MANAGED = "MANAGED"
    NONE = "NONE"


class EvidenceType(StrEnum):
    AI_OPINION = "AI_OPINION"
    RUNTIME_EVIDENCE = "RUNTIME_EVIDENCE"
    TOOL_EVIDENCE = "TOOL_EVIDENCE"
    DOCUMENT_EVIDENCE = "DOCUMENT_EVIDENCE"
    HUMAN_EVIDENCE = "HUMAN_EVIDENCE"


class AssuranceMode(StrEnum):
    FLEXIBLE = "FLEXIBLE"
    STANDARD = "STANDARD"
    VERIFIED = "VERIFIED"
